name: CI/CD - STAGE
on:
    push:
        branches:
            - main
    pull_request:
        types: [synchronize]
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

env:
    NODE_VERSION: 18.17.1
    BASE_URL: ${{ secrets.STAGE_BASE_URL }}

jobs:
    vrt-chromatic:
        name: 'Visual Regression Testing w. Chromatic'
        runs-on: ubuntu-latest
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '游댢  Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '游댢 Install dependencies'
              run: yarn install

            - name: '游깯 Run VRT w. Chromatic'
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              run: yarn test:chromatic

            - name: 'Package ./storybook'
              run: yarn run package

            - name: 'Upload apps artifact'
              uses: actions/upload-artifact@v3
              with:
                  name: storybook-${{ github.run_number }}-${{ github.run_id }}
                  path: './package/storybook/'

    build-n-package:
        name: 'Build & Package'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '游댢  Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '游댢 Install dependencies'
              run: yarn install

            - name: 'Run Build'
              run: yarn run build:prod

            - name: 'Package ./apps'
              run: yarn run package

            - name: 'Upload apps artifact'
              uses: actions/upload-artifact@v3
              with:
                  name: apps-${{ github.run_number }}-${{ github.run_id }}
                  path: './package/apps/'

    deploy-stage:
        name: 'Deploy to Netlify STAGE env.'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic, build-n-package]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Create package/dist'
              run: mkdir -p package/apps

            - uses: actions/download-artifact@v3
              with:
                  name: apps-${{ github.run_number }}-${{ github.run_id }}
                  path: package/apps

            # - name: '游댢 Setup Pages'
            #   if: steps.changed-test-files.outputs.any_changed == 'true'
            #   uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  # Upload entire repository
                  path: './package/apps'

            - name: '游 Deploy to Netlify TEST env.'
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: './package/apps'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.STAGE_NETLIFY_SITE_ID }}
              timeout-minutes: 1

            # snippet to deploy to GitHub Pages
            # - name: '游 Deploy to GitHub Pages'
            #   if: steps.changed-test-files.outputs.any_changed == 'true'
            #   id: deployment
            #   uses: actions/deploy-pages@v2

    deploy-storybook-stage:
        name: 'Deploy Storybook to Netlify STAGE env.'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Create package/storybook'
              run: mkdir -p package/storybook

            - uses: actions/download-artifact@v3
              with:
                  name: storybook-${{ github.run_number }}-${{ github.run_id }}
                  path: package/storybook

            - name: '游 Deploy to Netlify'
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: './package/storybook'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.STAGE_STORYBOOK_NETLIFY_SITE_ID }}
              timeout-minutes: 1
